### ISSUE TITLE
Feature request: converting single part email messages to multipart

### ISSUE THREAD

**Issue by andruska** [ohwgiles/wemed#4]
Currently when editing single part (text/plain or text/html) message with Wemed and I want to add Part → New Empty Part it would be nice to convert the whole thing to multipart, prompting type.
Thank you !

**Comment by andruska** [comment]
Currently, when adding new part (Part → New Empty Part) to single part message I get many errors:

(wemed:7350): Gtk-CRITICAL **: gtk_tree_store_get_value: assertion 'VALID_ITER (iter, tree_store)' failed

(wemed:7350): GLib-GObject-CRITICAL **: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed

(wemed:7350): gmime-CRITICAL **: g_mime_multipart_add: assertion 'GMIME_IS_MULTIPART (multipart)' failed

(wemed:7350): Gtk-CRITICAL **: gtk_tree_store_append: assertion 'VALID_ITER (parent, tree_store)' failed

(wemed:7350): Gtk-CRITICAL **: gtk_tree_store_set_valist: assertion 'VALID_ITER (iter, tree_store)' failed

**Comment by ohwgiles** [comment]
Hmm, I'm not sure I completely understand. Currently, at least for me, selecting "new empty part" finds the closest parent multipart node, and adds a new empty part there. So the new part becomes a sibling of the currently selected part. Do you mean to change this behavior? Would "new empty part" first insert a new multipart node at the current position then add a new empty part to it? What would happen to the currently selected node?

**Comment by andruska** [comment]
I think my terminology was unclear. Let's say that "single part" message looks like this:

Date: Fri, 7 Oct 2016 16:42:29 +0000
Subject: Sample subject
From: "Sender" <info@bbb.bb>
To: Receiver <info@hhh.hh>
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><p>Thats the sample body</p></html>

When I add Part → New Empty Part to this message, I can see error messages shown above. Adding new part to this single part message, for first we need to convert it to multipart message by changing Content-Type and then adding new MIME part. 
Result would look more or less like this:

Date: Fri, 7 Oct 2016 16:42:29 +0000
Subject: Sample subject
From: "Sender" <info@bbb.bb>
To: Receiver <info@hhh.hh>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_4db949f78d7c7ce7ce78eac44d81ff92"

--b1_4db949f78d7c7ce7ce78eac44d81ff92`

Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Thats the sample body

--b1_4db949f78d7c7ce7ce78eac44d81ff92

Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><p>Thats the sample body</p></html>

--b1_4db949f78d7c7ce7ce78eac44d81ff92--


Thank you !

**Comment by ohwgiles** [comment]
Understood, and pushed a patch. It doesn't prompt because that would introduce some more complex edge cases I don't want to deal with just now, e.g. two prompts in a row when you try to add a multipart node to a single-part document. Instead it automatically reparents to a new `multipart/mixed` node - you can easily change this type afterwards
