### ISSUE TITLE
Wemed crashes when repetedly selecting between text/html and text/plain MIME parts

### ISSUE THREAD

**Issue by andruska** [ohwgiles/wemed#6]
Also I discovered probably another bug too.

When I open file attached to previous issue and repetedly selecting between text/html and text/plain parts, Wemed crashes with different error messages.

$ wemed
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory
*** Error in `wemed': corrupted size vs. prev_size: 0x017497f8 ***
Aborted (core dumped)

$ wemed
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory
Segmentation fault (core dumped)

**Comment by ohwgiles** [comment]
I can reproduce this (the memory issue, not the xdg-mime errors). I'll investigate
